[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log

[program:watcher]
command=python3 /app/app/watcher/main.py
autostart=true
autorestart=true
stderr_logfile=/app/logs/watcher.err.log
stdout_logfile=/app/logs/watcher.out.log

[program:webui]
command=python3 /app/app/webui/server.py
autostart=true
autorestart=true
stderr_logfile=/app/logs/webui.err.log
stdout_logfile=/app/logs/webui.out.log

[program:rclone]
command=rclone rcd --rc-no-auth --rc-addr :5572
autostart=true
autorestart=true
stderr_logfile=/app/logs/rclone.err.log
stdout_logfile=/app/logs/rclone.out.log
